# Generated by Django 3.2 on 2025-12-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line', models.CharField(choices=[('Purple', 'Purple Line'), ('Green', 'Green Line'), ('Yellow', 'Yellow Line')], max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=100)),
                ('platforms', models.IntegerField()),
            ],
        ),
    ]
