# Generated by Django 3.2 on 2025-12-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('has_card', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MetroCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metro_card', to='metro.userprofile')),
            ],
        ),
    ]
