# Generated by Django 3.2 on 2025-12-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0002_metrocard_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrocard',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
